# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: cpp
   
install:
  - sudo apt-get install gfortran
  - wget "http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.3-p7.tar.gz"
#  - tar -xzf petsc-3.2-p7.tar.gz
#  - cd petsc-3.2-p7
#  - ./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --download-fblaslapack --download-mpich
#  - make all

  install:
  
