# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: cpp
   
install:
  - sudo apt-get install gfortran
  - sudo apt-get install libblas-dev libatlas-dev liblapack-dev libnetcdf-dev
  - wget "http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.3-p7.tar.gz" -O /tmp/petsc-3.3-p7.tar.gz
  - tar -xf /tmp/petsc-3.3-p7.tar.gz
  - cd petsc-3.3-p7
  - ./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --download-fblaslapack --download-mpich
  - make all
  - export PETSC_DIR=${PWD}
  - cd ..
  - wget "http://www.mcs.anl.gov/research/projects/tao/download/tao-2.0-p6.tar.gz" -O /tmp/tao-2.0-p6.tar.gz
  - tar -xf /tmp/tao-2.0-p6.tar.gz
  - cd tao-2.0-p6
  - export TAO_DIR=${PWD}
  - make all
  - cd ..
  - wget "ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.0.tar.gz" -O /tmp/netcdf-fortran-4.4.0.tar.gz
  - tar -xf /tmp/netcdf-fortran-4.4.0.tar.gz
  - cd netcdf-fortran-4.4.0
  - make check
  - sudo make install
  - cd ..
  
script: 
  - pwd
  - cd src
  - make rapid
  - 
  
  
